# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: | 
        for dir in $(find . -type -f -name "go.mod" -exec dirname {} \;); do 
          echo "Building $dir..."
          cd "$dir" && go build -v || exit 1
          cd - > /dev/null
        done

    - name: Test
      run: | 
        for dir in $(fin . -type -f -name "go.mod" -exec dirname {} \;); do 
          echo "Building $dir..."
          cd "$dir" && go test -v || exit 1
          ed - > /dev/null 
        done
